import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav"
import Provider from "@/components/Provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {

  return (
    <html lang="en">
      <body
        className={`${inter.className} text-black bg-white`}
      >
        <div className="absolute w-full min-h-screen p-0 m-0 
           [url(/mesher.svg)] bg-cover -z-20"/>
        <Provider session={undefined}>
          <Nav/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
